image: node:dubnium-alpine

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm run lint:js && npm run lint:scss

pages:
  stage: deploy
  script:
    - npm run build
    - cp -r build/* public
  artifacts:
    paths:
      - public
  only:
    - master
